server:
  port: 8085


  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql.BasicBinder: TRACE
        springframework:
          web: TRACE
          core: TRACE
      com:
        example:
          sandboxspring: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: samar
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        generate_statistics: true

  sql:
    init:
      mode: never
      schema-locations: ''
      data-locations: ''

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        thread-name-prefix: app-thread-

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: spring-boot-app
#            client-secret: KbhdS3uGvFsENF3tJfACXAerVcekYNCE
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email,roles
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/sandbox-realm
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/sandbox-realm

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    org.springframework:
      web: DEBUG
    com:
      example:
        sandboxspring: INFO
