import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { UserService, User } from 'src/app/services/user.service';
import { trigger, transition, style, animate } from '@angular/animations';

@Component({
  selector: 'app-add-user',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './add-user.component.html',
  styleUrls: ['./add-user.component.scss'],
  animations: [
    trigger('slideIn', [
      transition(':enter', [
        style({ transform: 'translateY(20px)', opacity: 0 }),
        animate('300ms ease-out', style({ transform: 'translateY(0)', opacity: 1 }))
      ]),
      transition(':leave', [
        animate('200ms ease-in', style({ transform: 'translateY(20px)', opacity: 0 }))
      ])
    ])
  ]
})
export class AddUserComponent {
  userForm: FormGroup;
  isSubmitting = false;
  showSuccessToast = false;
  showErrorToast = false;
  toastMessage = '';

  constructor(private fb: FormBuilder, private userService: UserService) {
    this.userForm = this.fb.group({
      username: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      role: ['ROLE_SCIENTIST', Validators.required],
      enabled: [true, Validators.required]
    });
  }

  onSubmit() {
    if (this.userForm.valid && !this.isSubmitting) {
      this.isSubmitting = true;
      this.hideToasts();

      const newUser: User = {
        username: this.userForm.value.username,
        email: this.userForm.value.email,
        password: this.userForm.value.password,
        role: this.userForm.value.role,
        enabled: this.userForm.value.enabled,
        validationCode: '' // Will be auto-generated by backend
      };

      this.userService.createUser(newUser).subscribe({
        next: (user) => {
          console.log('✅ Utilisateur créé:', user);
          this.showSuccessMessage('Utilisateur créé avec succès! 🎉');
          this.userForm.reset({
            role: 'ROLE_SCIENTIST',
            enabled: true,
            validationCode: ''
          });
          this.isSubmitting = false;
        },
        error: (error) => {
          console.error('❌ Erreur création utilisateur:', error);
          this.showErrorMessage(error.message || 'Erreur lors de la création de l\'utilisateur ❌');
          this.isSubmitting = false;
        }
      });
    } else {
      // Mark all fields as touched to show validation errors
      Object.keys(this.userForm.controls).forEach(key => {
        this.userForm.get(key)?.markAsTouched();
      });
    }
  }

  showSuccessMessage(message: string) {
    this.toastMessage = message;
    this.showSuccessToast = true;
    this.showErrorToast = false;
    
    // Auto hide after 4 seconds
    setTimeout(() => {
      this.hideToasts();
    }, 4000);
  }

  showErrorMessage(message: string) {
    this.toastMessage = message;
    this.showErrorToast = true;
    this.showSuccessToast = false;
    
    // Auto hide after 6 seconds
    setTimeout(() => {
      this.hideToasts();
    }, 6000);
  }

  hideToasts() {
    this.showSuccessToast = false;
    this.showErrorToast = false;
    this.toastMessage = '';
  }
}
